### PR TITLE
Payment API: endpoints for listing accounts

### PR DESCRIPTION
**Pull request by Wiezzel**
* GET /provider/accounts -- lists accounts in receive mode
* GET /requestor/accounts -- lists accounts in send mode

#### Testing instructions:

Start the payment API example:
```shell
$ cargo run --example payment_api
...
[2020-09-10T09:53:41Z INFO  ethkey] eth account EthAccount address: 0xeec0ee8e040addee4c65cc09c0d3e78f68f1ef56, path: "/home/adam/yagna/core/payment/provider.key" loaded
[2020-09-10T09:53:41Z INFO  ethkey] eth account EthAccount address: 0x0ccb64ef60c185dd39f42f791e4d12e96f66588f, path: "/home/adam/yagna/core/payment/requestor.key" loaded
...
```
Copy provider and requestor addresses printed in logs.

Run the get_accounts example to assert that accounts are properly listed.
```shell
$ cargo run --example get_accounts 0xeec0ee8e040addee4c65cc09c0d3e78f68f1ef56 0x0ccb64ef60c185dd39f42f791e4d12e96f66588f
[2020-09-10T09:48:00Z INFO  get_accounts] Checking provider account...
[2020-09-10T09:48:00Z INFO  get_accounts] OK.
[2020-09-10T09:48:00Z INFO  get_accounts] Checking requestor account...
[2020-09-10T09:48:00Z INFO  get_accounts] OK.
```

### CODE REVIEW

**Review by bidzyyys — COMMENTED** [review]
Code looks good!

**Review by maaktweluit — COMMENTED** [review]
Checked the code and tested it, LGTM!

Only the `ya-client` is not pointing to master now but (i think) the PR branch

Looks a bit strange to have:
```
Ok(Ok(accounts))
```

**Comment by Wiezzel** [comment]
> One small nit, this looks a bit strange:
> 
> ```
> Ok(Ok(accounts))
> ```

Well, alternative is introducing a block and using `??` but I don't find it pretty.

```rust
let all_accounts = match async move {
    Ok(bus::service(LOCAL_SERVICE).send(GetAccounts {}).await??)
}
.await {
    Ok(accounts) => accounts,
    Err(e) => return response::server_error(&e),
};
```

**Review by bidzyyys — APPROVED** [review]
It works!

**Review by maaktweluit — APPROVED** [review]
@Wiezzel thanks for the example :) now i see this is the lesser of the evils ;)

**Comment by etam** [comment]
this introduced a mismatch between Cargo.toml and Cargo.lock

**Pull request merged**
