### PR TITLE
Wkargul/new release notification

### PR DESCRIPTION
**Pull request by wkargul**
This PR consists of fix for "new release" notification. The main problem was with "rc" versions being reported as available for update. The second issue was redundant notification at yagna start.

Main issue solved with filter impl for "%rc%" versions fetched from local DB. What is more, I sealed github client reading the latest released versions of yagna. It is now reading only those with tag -> `latest`.

Second issue is solved with a slightly change in interval. `tick()` is replaced with `delay_for()` as we do not need this level of accuracy when counting the interval. `tick()` was also problematic as caused redundant logs at yagna startup (if newest yagna's version was avaialble).

It fixes https://github.com/golemfactory/yagna/issues/1819

### CODE REVIEW

**Review by maaktweluit — COMMENTED** [review]
LGTM!

One thought: it seems we still store the current version in BD if its an RC, maybe we should also filter before inserting?

**Comment by wkargul** [comment]
Hey @maaktweluit 
I would keep storing current running version. The only "rc" releases can be inserted into DB if we run "rc" intentionally. It might be helpful to have such record in db. What do you think? Suggestion about update for "rc" is no longer hinted by yagna, so the regular user is no longer spammed with irrelevant hints.

With commit `[c5456ed](https://github.com/golemfactory/yagna/pull/1854/commits/c5456ed4a4b20646a8b93bf505a5c3f01cd5509a)` I fixed fetching any other release than those having tag `latest` when checking running release. So at this point the only way to insert "rc" into DB is when running such version intentionally.

**Comment by maaktweluit** [comment]
> I would keep storing current running version. The only "rc" releases can be inserted into DB if we run "rc" intentionally. It might be helpful to have such record in db. What do you think?
The database table is there to notify users about the new released versions, storing the "rc" releases is not helping this goal in any way, only add complexity without functionality.
Unless we properly implement pre-release vs full release.

> Suggestion about update for "rc" is no longer hinted by yagna, so the regular user is no longer spammed with irrelevant hints.

This was the main goal of this change 👍  :)
> 
> With commit [c5456ed](https://github.com/golemfactory/yagna/pull/1854/commits/c5456ed4a4b20646a8b93bf505a5c3f01cd5509a) I fixed fetching any other releases than those having tag `latest` when checking running release. So at this point the only way to insert "rc" into DB is when running such version intentionally.
What do you mean by "running such version intentionaly"? when a normal user runs an RC this should not be store in the database, IMHO.

**Comment by wkargul** [comment]
If the database table is there to notify users about the new released versions it indeed does not make sense to store `-rc` releases there. I implemented `if` statement to omit DB update then.

I resigned from filtering `latest` releases when checking running release. We are fetching details of the release matching the specified version there, so it makes no sense to filter it by `latest` tag.

**Pull request merged**
