### PR TITLE
Yagna buildtime version

### PR DESCRIPTION
**Pull request by tworec**
I've made the latest tag (even lightweight) as the default version. Cargo version is just a fallback, when the `git describe --tag` does not work. When in context of Github Actions build number is added as a suffix `-b<build_no>`.

Here's an example

```
$ cargo run -- -V
   Compiling ya-compile-time-utils v0.1.0 (/Users/tworec/git/yagna/utils/compile-time-utils)
   Compiling yagna v0.5.0 (/Users/tworec/git/yagna)
    Finished dev [unoptimized + debuginfo] target(s) in 49.88s
     Running `target/debug/yagna -V`
yagna pre-rel-v0.5.0-495172ea
$ GITHUB_RUN_NUMBER=777 cargo run -- -V
   Compiling yagna v0.5.0 (/Users/tworec/git/yagna)
    Finished dev [unoptimized + debuginfo] target(s) in 44.93s
     Running `target/debug/yagna -V`
yagna pre-rel-v0.5.0-495172ea-b777
```

### EDIT:

Or even more

```
$ cargo run -- -V
   Compiling ya-compile-time-utils v0.1.0 (/Users/tworec/git/yagna/utils/compile-time-utils)
   Compiling yagna v0.5.0 (/Users/tworec/git/yagna)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 09s
     Running `target/debug/yagna -V`
yagna 0.5.0-495172ea (4bb3d301 2020-11-20)


$ GITHUB_RUN_NUMBER=777 cargo run -- -V
   Compiling ya-compile-time-utils v0.1.0 (/Users/tworec/git/yagna/utils/compile-time-utils)
   Compiling yagna v0.5.0 (/Users/tworec/git/yagna)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 28s
     Running `target/debug/yagna -V`
yagna 0.5.0-495172ea (4bb3d301 2020-11-20 build #777)
```

And unified with `golemsp`
```
$ cargo run -p golemsp -- -V
   Compiling ya-compile-time-utils v0.1.0 (/Users/tworec/git/yagna/utils/compile-time-utils)
   Compiling golemsp v0.1.0 (/Users/tworec/git/yagna/golem_cli)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 24s
     Running `target/debug/golemsp -V`
golemsp 0.5.0-495172ea (4bb3d301 2020-11-20)

$ GITHUB_RUN_NUMBER=777 cargo run -p golemsp -- -V
   Compiling ya-compile-time-utils v0.1.0 (/home/tworec/git/yagna/utils/compile-time-utils)
   Compiling golemsp v0.1.0 (/home/tworec/git/yagna/golem_cli)
    Finished dev [unoptimized + debuginfo] target(s) in 4.91s
     Running `target/debug/golemsp -V`
golemsp 0.5.0-495172ea (4bb3d301 2020-11-20 build #777)

$ cargo run -p golemsp setup
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 1m 10s
     Running `target/debug/golemsp setup`

                                             ```
                                             ```
                                             ```
                  ```                        ```
       `````````````        `````````        ```        `````````         ``````````````````
     ````      ```        ```       ```      ```      ```       ```       ```     ``     ```
     ``          ``      ```         ```     ```      ``         ```      ``      ``     ```
    ```          ``      ``           ``     ```     ```````````````      ``      ``     ```
     ``          ``      ```         ```     ```      ``                  ``      ``     ```
     ```       ```        ```       ```      ```      ```        `        ``      ``     ```
       `````````            `````````        ```        ``````````        ``      ``     ```
          ```
          ```               version: 0.5.0-495172ea
       `````````
     ```       ```          commit: 4bb3d301
     ``          ``
    ```          ``         build: -
     ``          ``
     ````      ```          date: 2020-11-20
       `````````

$ GITHUB_RUN_NUMBER=777 cargo run -p golemsp setup
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/golemsp setup`    ```
                  ```                        ```
                                             ```        `````````         ``````````````````
                                             ```      ```       ```       ```     ``     ```
                                             ```      ``         ```      ``      ``     ```
                  ```                        ```     ```````````````      ``      ``     ``*
       `````````````        `````````        ```        `````````         ``````````````````
     ````      ```        ```       ```      ```      ```       ```       ```     ``     ```
     ``          ``      ```         ```     ```      ``         ```      ``      ``     ```
    ```          ``      ``           ``     ```     ```````````````      ``      ``     ```
     ``          ``      ```         ```     ```      ``                  ``      ``     ```
     ```       ```        ```       ```      ```      ```        `        ``      ``     ```
       `````````            `````````        ```        ``````````        ``      ``     ```
          ```    ``
          ```               version: 0.5.0-495172ea
       ````````` ``
     ```       ```          commit: 4bb3d301
     ``          ``
    ```          ``         build: 777
     ``          ``
     ````      ```          date: 2020-11-20
       `````````

$ cargo run -p golemsp status
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 57.01s
     Running `target/debug/golemsp status`
┌───────────────────────────────────────────────────┐
│  Status                                           │
│                                                   │
│  Service    is not running                        │
│  Version    0.5.0-495172ea (4bb3d301 2020-11-20)  │
│                                                   │
│  Node Name  2rec-macbook-test                     │
│  Subnet     devnet-alpha.2                        │
└───────────────────────────────────────────────────┘

$ GITHUB_RUN_NUMBER=777 cargo run -p golemsp status
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/golemsp status`
┌──────────────────────────────────────────────────────────────┐
│  Status                                                      │
│                                                              │
│  Service    is not running                                   │
│  Version    0.5.0-495172ea (4bb3d301 2020-11-20 build #777)  │
│                                                              │
│  Node Name  2rec-reject-proposal-test-node@awokado           │
│  Subnet     devnet-alpha.2-mdt                               │
│  VM         valid                                            │
└──────────────────────────────────────────────────────────────┘

```

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]

**Comment by mfranciszkiewicz** [comment]
If a tag consists of more than version (i.e. `-495172ea`), the version is no longer compatible with the `semver` spec. Version metadata is prefixed with `+`, i.e. `0.5.0+b777`

**Comment by maaktweluit** [comment]
@mfranciszkiewicz Maybe we can fix this by changing the format of the tag we are using.

Looking at semver.org, we should use tags like:

`0.5.0-alpha.0`
`0.5.0-alpha.1`
`0.5.0-beta.0`
`0.5.0-rc.0`

Seems better not to include the SHA in the tag, they have differed often ( like in your OP examples ) creating confusion.

@tworec what do you think?

**Comment by tworec** [comment]
I think the pretty the same as you @maaktweluit 

@mfranciszkiewicz the semver spec allows pre-release notation with `-` (hyphen) sign followed by identifiers.
https://semver.org/#spec-item-9
We just need to follow this rule #9 when tagging:
- Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-].
- Identifiers MUST NOT be empty.
- Numeric identifiers MUST NOT include leading zeroes. 

is that ok with you? @mfranciszkiewicz

**Comment by maaktweluit** [comment]
👍 

Would also be nice to have some increment in the `identifiers` like alpha > beta > rc

**Comment by tworec** [comment]
I don't think we need to be strictly semver compliant when it comes to build metadata
https://semver.org/#spec-item-10 
I'd go with the notation of `(` and `)` after version, which in fact is not part of the version itself.

**Comment by tworec** [comment]
> 👍
> 
> Would also be nice to have some increment in the `identifiers` like `alpha > beta > rc` instead of random git tags

agreed. I've created this PR not to enforce us putting gitrev in tag name, as it is awkward and ugly, and counterintuitive and... lots of reasons ;)

**Comment by mfranciszkiewicz** [comment]
> I think the pretty the same as you @maaktweluit
> 
> @mfranciszkiewicz the semver spec allows pre-release notation with `-` (hyphen) sign followed by identifiers.
> https://semver.org/#spec-item-9
> We just need to follow this rule #9 when tagging:
> 
>     * Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-].
> 
>     * Identifiers MUST NOT be empty.
> 
>     * Numeric identifiers MUST NOT include leading zeroes.
> 
> 
> is that ok with you? @mfranciszkiewicz

`alpha.0` is still a part of the version, `495172ea` is just metadata. Lexical ordering (as in the spec) fails here - `495172ea` is not necessarily older than `deadbeef` and it's not obvious without looking at git history. That's why I suggested using `+metadata`

**Comment by maaktweluit** [comment]
> alpha.0 is still a part of the version, 495172ea is just metadata. Lexical ordering (as in the spec) fails here - 495172ea is not necessarily older than deadbeef and it's not obvious without looking at git history. That's why I suggested using +metadata

Fully agree! 

This is why we propose to remove the `495172ea` from the ( upcoming ) tags and replace it with `alpha.X`. ( x = number )
@mfranciszkiewicz Does that resolve the comment for you?

**Comment by mfranciszkiewicz** [comment]
> > alpha.0 is still a part of the version, [495172e](https://github.com/golemfactory/yagna/commit/495172eaff9ae93737c519f237a5fa8a193918ed) is just metadata. Lexical ordering (as in the spec) fails here - [495172e](https://github.com/golemfactory/yagna/commit/495172eaff9ae93737c519f237a5fa8a193918ed) is not necessarily older than deadbeef and it's not obvious without looking at git history. That's why I suggested using +metadata
> 
> Fully agree!
> 
> This is why we propose to remove the `495172ea` from the ( upcoming ) tags and replace it with `alpha.X`. ( x = number )
> @mfranciszkiewicz Does that resolve the comment for you?

👍 yes

**Comment by tworec** [comment]
cool! so pls one of you guys give green and I will merge it

**Comment by maaktweluit** [comment]
@golemfactory/ya-net or @golemfactory/exe-unit is required

**Review by mfranciszkiewicz — APPROVED** [review]

**Comment by tworec** [comment]
> > alpha.0 is still a part of the version, [495172e](https://github.com/golemfactory/yagna/commit/495172eaff9ae93737c519f237a5fa8a193918ed) is just metadata. Lexical ordering (as in the spec) fails here - [495172e](https://github.com/golemfactory/yagna/commit/495172eaff9ae93737c519f237a5fa8a193918ed) is not necessarily older than deadbeef and it's not obvious without looking at git history. That's why I suggested using +metadata
> 
> Fully agree!
> 
> This is why we propose to remove the `495172ea` from the ( upcoming ) tags and replace it with `alpha.X`. ( x = number )

For the record: commit sha aka gitrev will be part of build metadata between `(` and `)` as illustrated in examples above, so it is not needed in tag itself, and we claim even more, it MUST NOT be there, to the version be compatible with semver

**Pull request merged**
