### PR TITLE
github action to add and verify DoD with PRs

### PR DESCRIPTION
**Pull request by mateuszsrebrny**
:D look below \o/

### :ballot_box_with_check: Definition of Done checklist
- [x] The code is tested enough
- [x] Testability insights are recorded on https://www.notion.so/golemnetwork/Testability-a42886f72cb649129cddd65bc9dfe2b9

### CODE REVIEW

**Review by MrDarthShoe — APPROVED** [review]

**Comment by mateuszsrebrny** [comment]
@MrDarthShoe you did approve but didn't check the checkboxes... please do :D 
I shouldn't be the one checking them out :P

**Comment by wkargul** [comment]
I double-reviewed it and it looks good to me. I also checked the checkboxes and it's awesome

**Comment by mateuszsrebrny** [comment]
hm... they don't look checked to me :/ interesting

**Comment by wkargul** [comment]
> hm... they don't look checked to me :/ interesting

I unchecked it just to see what is happening then :P All works correctly. The only thing is about possible extra commit arrival. What is happening then? I updated my comment above with some more description.

**Comment by mateuszsrebrny** [comment]
> 

good catch :heart:
I don't see an easy way around that though :/

maybe we could agree that the reviewer doesn't checkout the checkboxes if their comments recommend doing changes so big that the testability topic should be revisited?

**Comment by wkargul** [comment]
> > 
> 
> good catch ❤️ I don't see an easy way around that though :/
> 
> maybe we could agree that the reviewer doesn't checkout the checkboxes if their comments recommend doing changes so big that the testability topic should be revisited?
> 
> ... and will check them out during the next round of review

Yep, that's fair! 👍

**Pull request merged**
