### PR TITLE
Move "task_package" from "srv.comp.wasm" to "srv.comp"

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**

### CODE REVIEW

**Comment by stranger80** [comment]
Just a note - this is in contradiction to the standards MVP cleanup exercise as per https://github.com/golemfactory/golem-architecture/pull/10

**Comment by mfranciszkiewicz** [comment]
> Just a note - this seems in contradiction to the standards MVP cleanup exercise as per [golemfactory/golem-architecture#10](https://github.com/golemfactory/golem-architecture/pull/10)?

I'd treat this PR as a temporary solution for making the `task_package` property more "generic" (i.e. not wasm specific and defined per runtime)

**Comment by stranger80** [comment]
@stranger80 I'd treat this PR as a temporary solution for making the task_package property more "generic" (i.e. not wasm specific and defined per runtime)

Oh, ok, cool.

**Comment by tworec** [comment]
included in #407

**Pull request closed without merging**
